// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddlirxzvlimdapumycfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbGlyeHp2bGltZGFwdW15Y2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDI0OTgsImV4cCI6MjA2NjUxODQ5OH0.mQ2BVvEyfdDBYC_CGSZ7vCBUISUVvBtrx61jPVVFhSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);